{
 "title": "Waterstream",
 "tags": [ "mqtt" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Messages Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mqtt_proxy_publish_received_total[2m]))",
     "legendFormat": "received rate, msg/sec"
    },
    {
     "expr": "sum(mqtt_proxy_publish_received_total)",
     "legendFormat": "received total count"
    },
    {
     "expr": "sum(rate(mqtt_proxy_published_to_kafka_total[2m]))",
     "legendFormat": "kafka publish rate, msg/sec"
    },
    {
     "expr": "sum(mqtt_proxy_published_to_kafka_total)",
     "legendFormat": "kafka total publish count"
    }
   ]
  },
  {
   "title": "Messages Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mqtt_proxy_publish_sent_total[2m]))",
     "legendFormat": "rate, msg/sec"
    },
    {
     "expr": "sum(mqtt_proxy_publish_sent_total)",
     "legendFormat": "total count"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mqtt_proxy_clients_current)",
     "legendFormat": "connected clients"
    }
   ]
  },
  {
   "title": "Client connections details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mqtt_proxy_connect_received_total)",
     "legendFormat": "CONNECT received"
    },
    {
     "expr": "sum(mqtt_proxy_accept_sent_total)",
     "legendFormat": "ACCEPT sent"
    },
    {
     "expr": "sum(mqtt_proxy_inactive_clients_disconnected_total)",
     "legendFormat": "Inactive clients disconnected"
    },
    {
     "expr": "sum(mqtt_proxy_connections_closed_total)",
     "legendFormat": "connections closed"
    },
    {
     "expr": "sum(mqtt_proxy_disconnect_received_total)",
     "legendFormat": "DISCONNECT received"
    },
    {
     "expr": "sum(mqtt_proxy_connect_rejected_total)",
     "legendFormat": "connections rejected"
    },
    {
     "expr": "sum(mqtt_proxy_overloaded_clients_disconnected_total)",
     "legendFormat": "overloaded disconnected"
    }
   ]
  },
  {
   "title": "Waterstream Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"waterstream-kafka\", area=\"heap\", service=\"waterstream\"}",
     "legendFormat": "Heap, bytes ({{instance}})"
    }
   ]
  },
  {
   "title": "MQTT Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mqtt_proxy_sessions_fresh_start_count_total)",
     "legendFormat": "Fresh sessions"
    },
    {
     "expr": "sum(mqtt_proxy_sessions_loaded_count_total)",
     "legendFormat": "Loaded sessions"
    },
    {
     "expr": "sum(mqtt_proxy_sessions_not_found_count_total)",
     "legendFormat": "Not found sessions"
    },
    {
     "expr": "sum(mqtt_proxy_sessions_load_duration_total)",
     "legendFormat": "Total sessions load duration, ms"
    }
   ]
  }
 ]
}